all: part1 part2

part1: part1.awk input.txt
	awk -f part1.awk input.txt

part2: part2.awk input.txt
	awk -f part2.awk input.txt

example1: part1.awk example1.txt
	awk -f part1.awk example1.txt

example2: part2.awk example2.txt
	awk -f part2.awk example2.txt
