all: part1 part2

part1: part1.bash input.txt
	bash part1.bash < input.txt

part2: part2.bash input.txt
	bash part2.bash < input.txt


example1: part1.bash example.txt
	bash part1.bash < example.txt

example2: part2.bash example.txt
	bash part2.bash < example.txt
